[build]
  publish = "dist/"
  functions = "netlify/functions/"
  command = "npm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run start"
  port = 3000
  publish = "dist"
